server:
  port: 9095

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbms
    username: Purnachander
    password: Purna@123
  jpa:
    properties:
      hibernate:
      format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true



  application:
    name: IDENTITY-SECURITY