server:
  port: 9090
#eureka:
#  client:
#    service-url:
#      defaultZone=http://eureka:password@localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://localhost:3306/sbms
    username: Purnachander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: product-service

